### ISSUE TITLE
JAVA CLI interface issues

### ISSUE THREAD

**Issue by ArturLorek** [nickrussler/email-to-pdf-converter#33]
I am getting the following issue when invoking the converter from the CLI by going:

java -jar emailconverter.jar -o "C:\Users\Artur\Documents\Email2PDF" "C:\Users\Artur\Documents\EmailTest\EmailTest.msg"

Start converting C:\Users\Artur\Documents\EmailTest\EmailTest.msg to C:\Users\Artur\Documents\Email2PDF
[main] INFO org.simplejavamail.outlookmessageparser.OutlookMessageParser - Could not parse directory entry __substg1.0_8004101F-00000000
java.lang.NumberFormatException: For input string: "101f-00000000"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at org.simplejavamail.outlookmessageparser.OutlookMessageParser.analyzeDocumentEntry(OutlookMessageParser.java:581)
        at org.simplejavamail.outlookmessageparser.OutlookMessageParser.getMessagePropertyFromDocumentEntry(OutlookMessageParser.java:399)
        at org.simplejavamail.outlookmessageparser.OutlookMessageParser.checkDirectoryDocumentEntry(OutlookMessageParser.java:262)
        at org.simplejavamail.outlookmessageparser.OutlookMessageParser.checkDirectoryEntry(OutlookMessageParser.java:208)
        at org.simplejavamail.outlookmessageparser.OutlookMessageParser.parseMsg(OutlookMessageParser.java:133)
        at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.parseOutlookMsg(OutlookEmailConverter.java:119)
        at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.outlookMsgToEmailBuilder(OutlookEmailConverter.java:62)
        at org.simplejavamail.converter.EmailConverter.outlookMsgToEmailBuilder(EmailConverter.java:226)
        at org.simplejavamail.converter.EmailConverter.outlookMsgToEmail(EmailConverter.java:209)
        at org.simplejavamail.converter.EmailConverter.outlookMsgToEML(EmailConverter.java:592)
        at org.simplejavamail.converter.EmailConverter.outlookMsgToEML(EmailConverter.java:583)
        at mimeparser.MimeMessageConverter.convertToPdf(MimeMessageConverter.java:123)
        at cli.Main.main(Main.java:123)
Mime Structure of C:\Users\Artur\Documents\EmailTest\EmailTest.msg:
-----------Mime Message-----------
> multipart/related
> |  multipart/alternative
> |  |  text/plain
> |  |  text/html
> |  image/gif; inline
> |  image/gif; inline
----------------------------------
Extract the inline images
Start conversion to pdf
Loading pages (1/6)
Error: Failed to load cid:image001.gif@01D5A9B1.70331880, with network status code 301 and http status code 0 - Protocol "cid" is unknown
Error: Failed to load cid:image002.gif@01D5A9B1.70331880, with network status code 301 and http status code 0 - Protocol "cid" is unknown
QPainter::begin(): Returned false============================] 100%
Error: Unable to write to destination
Exit with code 1 due to network error: ProtocolUnknownError
Conversion finished

I have the wkhtmltopdf.exe PATH added to system environment variables, it also is present in the installation directory of the EmailConverter, next to the JAR that is invoked.

I shall add that with the GUI in windows - there are no issues with the same file and conversion is successful in a blink of an eye.
Could you please advise ?

**Comment by nickrussler** [comment]
For the output parameter you need to specify a file path and not a directory. Maybe this would work in your case:
<pre>
java -jar emailconverter.jar -o "C:\Users\Artur\Documents\Email2PDF<b>\EmailTest.pdf</b>" "C:\Users\Artur\Documents\EmailTest\EmailTest.msg"
</pre>
