### ISSUE TITLE
Nested Msg. emailAddressList is required

### ISSUE THREAD

**Issue by MichaelPeter** [nickrussler/email-to-pdf-converter#36]
Hi Nick,

the attached msg has a msg inside a msg and another msg and one of them seem to have no adress...

[MailInMailInMail With Picture.msg.txt](https://github.com/nickrussler/email-to-pdf-converter/files/6561299/MailInMailInMail.With.Picture.msg.txt)
 

```

Start converting C:\Users\micha\Desktop\TestMsgToPdfFiles\MailInMailInMail With Picture.msg to C:\Users\micha\Desktop\TestMsgToPdfFiles\MailInMailInMail With Picture.pdf
[Thread-3] WARN org.simplejavamail.outlookmessageparser.model.OutlookMessage - Skipping nested Outlook message as file attachment, writing Outlook messages back as data is not supported!
[Thread-3] WARN org.simplejavamail.outlookmessageparser.model.OutlookMessage - To access the nested Outlook message as parsed Java object, refer to .getAttachments() instead.
The email could not be converted. Error: java.lang.IllegalArgumentException: emailAddressList is required
	at org.simplejavamail.internal.util.Preconditions.verifyNonnull(Preconditions.java:41)
	at org.simplejavamail.internal.util.Preconditions.checkNonEmptyArgument(Preconditions.java:30)
	at org.simplejavamail.internal.util.MiscUtil.extractEmailAddresses(MiscUtil.java:165)
	at org.simplejavamail.email.internal.EmailPopulatingBuilderImpl.withRecipients(EmailPopulatingBuilderImpl.java:1422)
	at org.simplejavamail.email.internal.EmailPopulatingBuilderImpl.to(EmailPopulatingBuilderImpl.java:835)
	at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.copyReceiversFromOutlookMessage(OutlookEmailConverter.java:132)
	at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.buildEmailFromOutlookMessage(OutlookEmailConverter.java:97)
	at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.buildEmailFromOutlookMessage(OutlookEmailConverter.java:114)
	at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.outlookMsgToEmailBuilder(OutlookEmailConverter.java:78)
	at org.simplejavamail.converter.EmailConverter.outlookMsgToEmailBuilder(EmailConverter.java:229)
	at org.simplejavamail.converter.EmailConverter.outlookMsgToEmail(EmailConverter.java:211)
	at org.simplejavamail.converter.EmailConverter.outlookMsgToEML(EmailConverter.java:595)
	at org.simplejavamail.converter.EmailConverter.outlookMsgToEML(EmailConverter.java:586)
	at mimeparser.MimeMessageConverter.convertToPdf(MimeMessageConverter.java:123)
	at cli.Main.main(Main.java:123)
	at gui.MainWindow.startConversion(MainWindow.java:361)
	at gui.MainWindow.access$400(MainWindow.java:43)
	at gui.MainWindow$8$1.run(MainWindow.java:281)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by nickrussler** [comment]
Seems to work now in the newest version
![image](https://github.com/nickrussler/email-to-pdf-converter/assets/1096768/14fefbe3-4769-433b-a8a7-378fc22465a4)
