### ISSUE TITLE
Crash on emailAddressList is required

### ISSUE THREAD

**Issue by gleporeNARA** [nickrussler/email-to-pdf-converter#41]
I get the below error on converting quite a few of my legacy emails. Unfortunately I cannot share the emails due to PII issues. Would it be possible to force the conversion despite errors like this?

Start converting Prisoner_numbers.msg to Prisoner_numbers.pdf
The email could not be converted. Error: java.lang.IllegalArgumentException: emailAddressList is required
        at org.simplejavamail.internal.util.Preconditions.verifyNonnull(Preconditions.java:41)
        at org.simplejavamail.internal.util.Preconditions.checkNonEmptyArgument(Preconditions.java:30)
        at org.simplejavamail.internal.util.MiscUtil.extractEmailAddresses(MiscUtil.java:165)
        at org.simplejavamail.email.internal.EmailPopulatingBuilderImpl.withRecipients(EmailPopulatingBuilderImpl.java:1422)
        at org.simplejavamail.email.internal.EmailPopulatingBuilderImpl.to(EmailPopulatingBuilderImpl.java:835)
        at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.copyReceiversFromOutlookMessage(OutlookEmailConverter.java:132)
        at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.buildEmailFromOutlookMessage(OutlookEmailConverter.java:97)
        at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.outlookMsgToEmailBuilder(OutlookEmailConverter.java:78)
        at org.simplejavamail.converter.EmailConverter.outlookMsgToEmailBuilder(EmailConverter.java:229)
        at org.simplejavamail.converter.EmailConverter.outlookMsgToEmail(EmailConverter.java:211)
        at org.simplejavamail.converter.EmailConverter.outlookMsgToEML(EmailConverter.java:595)
        at org.simplejavamail.converter.EmailConverter.outlookMsgToEML(EmailConverter.java:586)
        at mimeparser.MimeMessageConverter.convertToPdf(MimeMessageConverter.java:123)
        at cli.Main.main(Main.java:123)

**Comment by dgcruzing** [comment]
Seems to be the type of email version as I just run some tests as had the same problem. 
Saved the emails again in the new Outlook .msg format and still the same. 

Might be a permissions type on the email as its "emailAddressList is required" is causing this.

**Comment by nickrussler** [comment]
Can you check if this problem still exists in the newest version?

**Comment by nickrussler** [comment]
I assume this is also fixed, since the same error was reported here and tested to be fixed:

https://github.com/nickrussler/email-to-pdf-converter/issues/36

**Comment by gleporeNARA** [comment]
Unfortunately I no longer have access to the emails that were causing the issues. I will test again when I get another set of MSG files to convert.
