### ISSUE TITLE
NullPointer Exception on .msg file

### ISSUE THREAD

**Issue by duckduckgrayduck** [nickrussler/email-to-pdf-converter#67]
The email could not be converted. 
Error: java.lang.NullPointerException
	at org.simplejavamail.outlookmessageparser.model.OutlookMessage.filterRecipients(OutlookMessage.java:684)
	at org.simplejavamail.outlookmessageparser.model.OutlookMessage.getCcRecipients(OutlookMessage.java:669)
	at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.copyReceiversFromOutlookMessage(OutlookEmailConverter.java:134)
	at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.buildEmailFromOutlookMessage(OutlookEmailConverter.java:97)
	at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.outlookMsgToEmailBuilder(OutlookEmailConverter.java:78)
	at org.simplejavamail.converter.EmailConverter.outlookMsgToEmailBuilder(EmailConverter.java:229)
	at org.simplejavamail.converter.EmailConverter.outlookMsgToEmail(EmailConverter.java:211)
	at org.simplejavamail.converter.EmailConverter.outlookMsgToEML(EmailConverter.java:595)
	at org.simplejavamail.converter.EmailConverter.outlookMsgToEML(EmailConverter.java:586)
	at mimeparser.MimeMessageConverter.convertToPdf(MimeMessageConverter.java:123)
	at cli.Main.main(Main.java:123)

Here is the file:
https://drive.google.com/file/d/1H5hfhe4wY731zMP8Max-KYxUWcegsE3o/view?usp=sharing

**Comment by nickrussler** [comment]
Fixed in https://github.com/nickrussler/email-to-pdf-converter/releases/tag/2.9.0
