### ISSUE TITLE
Conversion fails if subject-line is missing in the eml-file

### ISSUE THREAD

**Issue by mrchang0815** [nickrussler/email-to-pdf-converter#74]
**Describe the bug**
It seems that I turned into a street of bad luck with my iPhone mail senders ("sent from my iPhone"): There really are people that send mails with missing subject. In this case email-to-pdf-converter throws the following error:

The email could not be converted. Error: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "subject" is null
	at mimeparser.MimeMessageConverter.parseSubject(MimeMessageConverter.java:512)
	at mimeparser.MimeMessageConverter.convertToPdf(MimeMessageConverter.java:134)
	at cli.Main.main(Main.java:126)
	at gui.MainWindow.startConversion(MainWindow.java:372)
	at gui.MainWindow.access$400(MainWindow.java:43)
	at gui.MainWindow$8$1.run(MainWindow.java:287)
	at java.base/java.lang.Thread.run(Thread.java:1583)

You may reproduce this with any eml-file where you have to delete the _whole_ 'Subject: xyz' line.

**Comment by nickrussler** [comment]
Hi, thanks for reports! Makes it better :)

Can you check if the fix in https://github.com/nickrussler/email-to-pdf-converter/pull/75  works:

https://github.com/nickrussler/email-to-pdf-converter/actions/runs/9552980627/artifacts/1609825004

**Comment by mrchang0815** [comment]
Hi,
mission accomplished! Works perfect. Thank you twice for your code care.
Regards,
mrchang0815
