### ISSUE TITLE
Support for MSG files in Richtext format

### ISSUE THREAD

**Issue by V00id** [nickrussler/email-to-pdf-converter#79]
Hello,

if I try to convert an Outlook E-mail (MSG) which was created in RTF format, it produces some sort of plain text with format terms.
I have attached a zip file with the original msg file and the result pdf.

Regards,
V0id.
[Test_Richtext.zip](https://github.com/user-attachments/files/17833908/Test_Richtext.zip)

**Comment by HarishA-Lexel** [comment]
Hi
I have saved .eml file to .msg file. And then tried to convert the .msg file to PDF. I get following error.
The email could not be converted. Error: java.lang.IllegalStateException: This should never happen
	at org.simplejavamail.converter.EmailConverter.mimeMessageToEML(EmailConverter.java:659)
	at org.simplejavamail.converter.EmailConverter.emailToEML(EmailConverter.java:669)
	at org.simplejavamail.converter.EmailConverter.outlookMsgToEML(EmailConverter.java:720)
	at org.simplejavamail.converter.EmailConverter.outlookMsgToEML(EmailConverter.java:711)
	at mimeparser.MimeMessageConverter.convertToPdf(MimeMessageConverter.java:125)
	at cli.Main.main(Main.java:126)
	at com.legalcraft.emlconversion.MSGConverter.convertSimpleMSGToPDF(MSGConverter.java:99)
	at com.legalcraft.emlconversion.MSGConverter.main(MSGConverter.java:15)

Can you let me know what could be the issue?

**Comment by HarishA-Lexel** [comment]
More error message
Caused by: jakarta.mail.internet.ParseException: In parameter list < > , expected ';', got "
at jakarta.mail.internet.ParameterList.<init>(ParameterList.java:290)
	at jakarta.mail.internet.ContentType.<init>(ContentType.java:93)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1486)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1148)
	at jakarta.mail.internet.MimeMultipart.updateHeaders(MimeMultipart.java:498)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1509)
	at jakarta.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2246)
	at jakarta.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2206)
	at jakarta.mail.internet.MimeMessage.writeTo(MimeMessage.java:1885)
	at jakarta.mail.internet.MimeMessage.writeTo(MimeMessage.java:1862)
	at org.simplejavamail.converter.internal.mimemessage.ImmutableDelegatingSMTPMessage.writeTo(ImmutableDelegatingSMTPMessage.java:272)
	at org.simplejavamail.converter.EmailConverter.mimeMessageToEML(EmailConverter.java:655)
	... 7 more
